# Tab-completion
autoload -Uz compinit
compinit

# Command correction
setopt correctall

# Prompt setup.
export PS1=$'%{\033]0;%m\007%}%{\e[0;36m%}%* %{\e[1;32m%}%n%{\e[0;37m\%}@%{\e[1;34m%}%m %{\e[1;31m%} %~\n%{\e[0;37m%}%# '

## History opts
export HISTSIZE=10000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE
setopt hist_expire_dups_first
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt appendhistory
setopt inc_append_history
setopt share_history

# Set bash like globbing.
unsetopt extendedglob

#allow tab completion in the middle of a word
setopt complete_in_word

## never ever beep ever
unsetopt beep
setopt NO_BEEP

#Reverse history search
bindkey '^R' history-incremental-search-backward

# viins keymap for ZLE
bindkey -v

zstyle :compinstall filename '/home/beowuff/.zshrc'

